# Application problem

In [1]:
%config Completer.use_jedi = False

In [7]:
from scipy.signal import correlate2d
import numpy as np

In [5]:
input_matrix = np.array([[3, 0, 9, 1, 2],
                        [5, 1, 2, 0, 7],
                        [8, 2, 4, 1, 3],
                        [2, 1, 5, 3, 6],
                        [4, 1, 6, 2, 7]])

kernel_matrix = np.array([[2, 0, 1],
                         [2, 0, 1],
                         [2, 0, 1]])

In [9]:
correlate2d(input_matrix, kernel_matrix, mode='valid')

array([[47,  8, 42],
       [41, 12, 38],
       [43, 14, 46]])

In [29]:
input_matrix = np.array([[[9, 10, 6, 2],
                          [2, 1, 4, 8],
                          [9, 0, 7, 1],
                          [8, 8, 3, 3]],
                         [[6, 7, 2, 10],
                          [1, 2, 6, 9],
                          [6, 4, 3, 5],
                          [8, 0, 1, 2]]])

In [30]:
input_matrix = input_matrix.reshape(2, 4, 4, 1)
input_matrix

array([[[[ 9],
         [10],
         [ 6],
         [ 2]],

        [[ 2],
         [ 1],
         [ 4],
         [ 8]],

        [[ 9],
         [ 0],
         [ 7],
         [ 1]],

        [[ 8],
         [ 8],
         [ 3],
         [ 3]]],


       [[[ 6],
         [ 7],
         [ 2],
         [10]],

        [[ 1],
         [ 2],
         [ 6],
         [ 9]],

        [[ 6],
         [ 4],
         [ 3],
         [ 5]],

        [[ 8],
         [ 0],
         [ 1],
         [ 2]]]])

In [17]:
import tensorflow as tf

In [31]:
p_out = tf.nn.max_pool2d(input_matrix, ksize=2, strides=2, padding='VALID')

In [32]:
p_out.numpy()

array([[[[10.],
         [ 8.]],

        [[ 9.],
         [ 7.]]],


       [[[ 7.],
         [10.]],

        [[ 8.],
         [ 5.]]]], dtype=float32)