In [1]:
%config Completer.use_jedi = False

# Load wine data

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

In [4]:
train_input, test_input, train_target, test_target = train_test_split(data, target, random_state=42, test_size=0.2)

# Build a random forest model

In [5]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

In [6]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)

In [7]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.9973541965122431
0.8905151032797809


In [8]:
rf.fit(train_input, train_target)
rf.feature_importances_

array([0.23167441, 0.50039841, 0.26792718])

In [9]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8934000384837406


# Extra Tress

In [10]:
from sklearn.ensemble import ExtraTreesClassifier

In [11]:
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, n_jobs=-1, return_train_score=True)

In [12]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.9974503966084433
0.8887848893166506


In [13]:
et.fit(train_input, train_target)
et.feature_importances_

array([0.20183568, 0.52242907, 0.27573525])

# Gradient booting

In [14]:
from sklearn.ensemble import GradientBoostingClassifier

In [15]:
gd = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gd, train_input, train_target, n_jobs=-1, return_train_score=True)

In [16]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.8881086892152563
0.8720430147331015


In [17]:
gd = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gd, train_input, train_target, n_jobs=-1, return_train_score=True)

In [18]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.9464595437171814
0.8780082549788999


In [19]:
gd.fit(train_input, train_target)
gd.feature_importances_

array([0.15872278, 0.68010884, 0.16116839])

# Histogram-based gradient booting

In [20]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

In [21]:
hgd = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgd, train_input, train_target, return_train_score=True)

In [22]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.9321723946453317
0.8801241948619236


In [23]:
from sklearn.inspection import permutation_importance

In [24]:
hgd.fit(train_input, train_target)
result = permutation_importance(hgd, train_input, train_target, n_repeats=10, random_state=42, n_jobs=-1)

In [25]:
result.importances_mean

array([0.08876275, 0.23438522, 0.08027708])

In [26]:
result = permutation_importance(hgd, test_input, test_target, n_repeats=10, random_state=42, n_jobs=-1)
result.importances_mean

array([0.05969231, 0.20238462, 0.049     ])

In [27]:
hgd.score(test_input, test_target)

0.8723076923076923

# XGBoost

In [28]:
from xgboost import XGBClassifier

In [30]:
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True)

/Users/jaehwanglee/tensorflow2_p38/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:10:34] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/Users/jaehwanglee/tensorflow2_p38/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/jaehwanglee/tensorflow2_p38/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:10:34] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[21:10:35] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/Users/jaehwanglee/tensorflow2_p38/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/jaehwanglee/tensorflow2_p38/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:10:35] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[21:10:35] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [32]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.9555033709953124
0.8799326275264677


# LightBGM

In [35]:
from lightgbm import LGBMClassifier

In [44]:
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)

In [46]:
print(np.mean(scores['train_score']))
print(np.mean(scores['test_score']))

0.935828414851749
0.8801251203079884
